---
- name: set hostname
  tags:
    - setup
    - setup.init
  sudo: yes
  command: hostnamectl set-hostname {{hostname}} --static

- name: upgrade all packages
  tags:
    - setup
    - setup.update
    - ocaml
  sudo: yes
  dnf: name=* state=latest

- name: get tz
  tags:
    - setup
    - setup.init
  shell: timedatectl | grep 'Time zone'
  register: tz

- name: change tz to JST
  tags:
    - setup
    - setup.init
  sudo: yes
  command: timedatectl set-timezone Asia/Tokyo
  when: tz.stdout.find('Asia/Tokyo') == -1

- name: install the 'Development tools' package group
  tags:
    - setup
    - setup.devel
  sudo: yes
  dnf: name="@Development tools" state=present

- name: install tmux
  tags:
    - setup
    - setup.devel
  sudo: yes
  dnf: name=tmux state=latest

- name: install msmtp
  tags:
    - setup
    - setup.devel
  sudo: yes
  dnf: name=msmtp state=latest

- name: create work dir
  tags:
    - setup
  sudo: yes
  file: path="{{work_dir}}" state=directory

- name: create misc dir
  tags:
    - setup
  file: path="~/misc" state=directory

# vim:st=2 sts=2 sw=2:
