---

- name: check-update
  sudo: yes
  command: dnf check-update

- name: update all
  sudo: yes
  command: dnf upgrade -y

- name: get tz
  shell: timedatectl | grep 'Time zone'
  register: tz

- name: change tz to JST
  sudo: yes
  command: timedatectl set-timezone Asia/Tokyo
  when: tz.stdout.find('Asia/Tokyo') == -1
