---
- name: set hostname
  tags:
    - setup
    - setup.init
  sudo: yes
  command: hostnamectl set-hostname fedora --static

- name: upgrade all packages
  tags:
    - setup
    - setup.update
  sudo: yes
  dnf: name=* state=latest

- name: get tz
  tags:
    - setup
    - setup.init
  shell: timedatectl | grep 'Time zone'
  register: tz

- name: change tz to JST
  tags:
    - setup
    - setup.init
  sudo: yes
  command: timedatectl set-timezone Asia/Tokyo
  when: tz.stdout.find('Asia/Tokyo') == -1

- name: install the 'Development tools' package group
  tags:
    - setup
    - setup.devel
  sudo: yes
  dnf: name="@Development tools" state=present

- name: install tmux
  tags:
    - setup
    - setup.devel
  sudo: yes
  dnf: name=tmux state=latest

- name: create work dir
  tags:
    - setup
  sudo: yes
  file: path="{{work_dir}}" state=directory

- name: create misc dir
  tags:
    - setup
  file: path="~/misc" state=directory

- name: check dotfiles existance
  tags:
    - setup
    - setup.vim
  ignore_errors: yes
  command: test -d "~/misc/dotfiles"
  register: exists_dotfiles

- name: clone dotfiles
  tags:
    - setup
    - setup.vim
  command: git clone git://github.com/jptomo/dotfiles.git dotfiles
  args:
    chdir: "~/misc"
  when: exists_dotfiles.rc == 1

- name: remove origin
  tags:
    - setup
  command: git remote rm origin
  args:
    chdir: "~/misc/dotfiles"
  when: exists_dotfiles.rc == 1

- name: add origin
  tags:
    - setup
  command: git remote add origin git@github.com:jptomo/dotfiles.git
  args:
    chdir: "~/misc/dotfiles"
  when: exists_dotfiles.rc == 1

- name: init rcs
  tags:
    - setup
    - setup.init
  command: sh setup.sh
  args:
    chdir: "~/misc/dotfiles"
  when: exists_dotfiles.rc == 1

# vim:st=2 sts=2 sw=2:
