se showtabline=2 " タブを常に表示
se nonumber      " 行番号非表示

se guifont=Migu\ 2M\ 11
se clipboard=unnamedplus
se guioptions-=T

if has('gui_macvim')
    se backspace=indent,eol,start
    se antialias
    se guifont=Migu\ 2M:h12
    se ambiwidth=double
    se clipboard=unnamed
    se columns=205 lines=55
    se imdisable
endif
