---
- stat: path="{{ python2_prefix }}/bin/python{{python2.bin_ver}}"
  register: stat_python2_bin
  tags:
    - python2

- name: install the 'Development tools' package group
  tags:
    - setup
  sudo: yes
  dnf: name="@Development tools" state=present
  when: not stat_python2_bin.stat.exists

- name: install build depends
  tags:
    - python2
  sudo: yes
  dnf: name={{item}} state=present
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - gdbm-devel
    - db4-devel
    - libpcap-devel
    - xz-devel
    - tk-devel
    - tcl-devel
    - expat-devel
  when: not stat_python2_bin.stat.exists

- name: clear work dir
  tags:
    - python2
  sudo: yes
  file: >-
    path="{{python2_build_dir}}"
    state=absent
  when: not stat_python2_bin.stat.exists

- name: create work dir
  tags:
    - python2
  sudo: yes
  file: >-
    path="{{python2_build_dir}}"
    state=directory mode=0777
  when: not stat_python2_bin.stat.exists

- name: download src
  tags:
    - python2
  get_url: >-
    url=https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz
    dest="{{python2_src}}"
    sha256sum="eda8ce6eec03e74991abb5384170e7c65fcd7522e409b8e83d7e6372add0f12a"
  when: not stat_python2_bin.stat.exists

- name: unarchive
  tags:
    - python2
  unarchive: >-
    src="{{python2_src}}"
    dest="{{python2_build_dir}}"
  when: not stat_python2_bin.stat.exists

- name: configure
  tags:
    - python2
  command: >-
    ./configure
    --prefix="{{python2_prefix}}"
    --enable-unicode=ucs4
    chdir="{{python2_src_dir}}"
  when: not stat_python2_bin.stat.exists

- name: make
  tags:
    - python2
  command: >-
    make
    chdir="{{python2_src_dir}}"
  when: not stat_python2_bin.stat.exists

- name: mkdir install path
  tags:
    - python2
  sudo: yes
  file: >-
    path="{{python2_prefix}}"
    state=directory
  when: not stat_python2_bin.stat.exists

- name: make install
  tags:
    - python2
  sudo: yes
  command: >-
    make install
    chdir="{{python2_src_dir}}"
  when: not stat_python2_bin.stat.exists

# vim:st=2 sts=2 sw=2:
