---
- stat: path="{{ vim_prefix }}/bin/vim"
  register: stat_vim_bin
  tags:
    - setup
    - setup.vim

- name: install build depends
  tags:
    - setup
    - setup.vim
  sudo: yes
  dnf: name={{item}} state=present
  with_items:
    - git
    - gcc
    - make
    - autoconf
    - ncurses-devel
    - perl-devel
    - perl-ExtUtils-Embed
    - ruby-devel
    - python-devel
    - python3-devel
    - lua-devel
    - luajit-devel
    - gtk2-devel
    - libXt-devel
  when: not stat_vim_bin.stat.exists

- name: clear work dir
  tags:
    - setup
    - setup.vim
  sudo: yes
  file: >-
    path="{{vim_build_dir}}"
    state=absent
  when: not stat_vim_bin.stat.exists

- name: create work dir
  tags:
    - setup
    - setup.vim
  sudo: yes
  file: >-
    path="{{vim_build_dir}}"
    state=directory mode=0777
  when: not stat_vim_bin.stat.exists

- name: clone src
  tags:
    - setup
    - setup.vim
  git: >-
    repo=https://github.com/vim/vim.git
    dest="{{vim_build_dir}}"
    version="{{vim_ver}}"
    force=yes
  when: not stat_vim_bin.stat.exists

- name: make autoconf
  tags:
    - setup
    - setup.vim
  command: >-
    make autoconf
    chdir="{{vim_build_dir}}/src"
  when: not stat_vim_bin.stat.exists

- name: configure
  tags:
    - setup
    - setup.vim
  command: >-
    ./configure
    --prefix="{{vim_prefix}}"
    --with-features=huge
    --without-x
    --disable-gui
    --enable-multibyte
    --enable-perlinterp=dynamic
    --enable-pythoninterp=dynamic
    --enable-rubyinterp=dynamic
    --enable-luainterp=dynamic
    --with-lua-prefix=/usr
    --with-luajit
    --enable-gpm
    --enable-cscope
    --enable-fontset
    --enable-fail-if-missinga
    chdir="{{vim_build_dir}}/src"
  when: not stat_vim_bin.stat.exists

- name: make
  tags:
    - setup
    - setup.vim
  command: >-
    make
    chdir="{{vim_build_dir}}/src"
  when: not stat_vim_bin.stat.exists

- name: mkdir install path
  tags:
    - setup
    - setup.vim
  sudo: yes
  file: >-
    path="{{vim_prefix}}"
    state=directory
  when: not stat_vim_bin.stat.exists

- name: make install
  tags:
    - setup
    - setup.vim
  sudo: yes
  command: >-
    make install
    chdir="{{vim_build_dir}}/src"
  when: not stat_vim_bin.stat.exists

# vim:st=2 sts=2 sw=2:
