---
- name: check dotfiles existance
  tags:
    - setup
    - setup.vim
  ignore_errors: yes
  command: test -d "~/misc/dotfiles"
  register: exists_dotfiles

- name: clone dotfiles
  tags:
    - setup
    - setup.vim
  git: repo=https://github.com/jptomo/dotfiles.git dest="~/misc/dotfiles"
  when: exists_dotfiles.rc == 1

- name: remove origin
  tags:
    - setup
  command: git remote rm origin
  args:
    chdir: "~/misc/dotfiles"
  when: exists_dotfiles.rc == 1

- name: add origin
  tags:
    - setup
  command: git remote add origin git@github.com:jptomo/dotfiles.git
  args:
    chdir: "~/misc/dotfiles"
  when: exists_dotfiles.rc == 1

- name: init rcs
  tags:
    - setup
    - setup.init
  command: sh setup.sh
  args:
    chdir: "~/misc/dotfiles"
  when: exists_dotfiles.rc == 1

- name: create bundle dir
  tags:
    - setup
    - setup.vim
  file: >-
    path="~/.vim/bundle"
    state=directory

- name: clone neobundle.vim
  tags:
    - setup
    - setup.vim
  git: >-
    repo=https://github.com/Shougo/neobundle.vim.git
    dest="~/.vim/bundle/neobundle.vim"
    force=yes

- name: clone vimproc.vim
  tags:
    - setup
    - setup.vim
  git: >-
    repo=https://github.com/Shougo/vimproc.vim.git
    dest="~/.vim/bundle/vimproc.vim"
    force=yes

- stat: path="~/.vim/bundle/vimproc.vim/autoload/vimproc_linux64.so"
  register: stat_vimproc_linux64_so

- name: make vimproc.vim
  tags:
    - setup
    - setup.vim
  command: >-
    make
    chdir="~/.vim/bundle/vimproc.vim"
  when: not stat_vimproc_linux64_so.stat.exists

- name: init bundles
  tags:
    - setup
    - setup.vim
  command: >-
    {{ vim_prefix }}/bin/vim
    -N -U NONE -i NONE -V1 -e -s
    --cmd "set encoding=utf-8"
    --cmd "set termencoding=utf-8"
    --cmd "source ~/.vimrc"
    --cmd "NeoBundleInstall!"
    --cmd "qall!"
  ignore_errors: yes
  when: exists_vim.rc == 1

- name: add path
  tags:
    - setup
    - setup.vim
  command: >-
    sed -i -e
    's!^#export PATH="$VIM:$PATH"$!export PATH="/opt/vim/v7.4.827/bin:$PATH"!'
    ~/.bash.include
  #when: exists_vim.rc == 1

# vim:st=2 sts=2 sw=2:
