---
- stat: path="~/misc/dotfiles"
  register: stat_dotfiles
  tags:
    - setup
    - setup.dots

- name: clone dotfiles
  tags:
    - setup
    - setup.dots
  git: repo=https://github.com/jptomo/dotfiles.git dest="~/misc/dotfiles"
  when: not stat_dotfiles.stat.exists

- name: remove origin
  tags:
    - setup
    - setup.dots
  command: git remote rm origin
  args:
    chdir: "~/misc/dotfiles"
  when: not stat_dotfiles.stat.exists

- name: add origin
  tags:
    - setup
    - setup.dots
  command: git remote add origin git@github.com:jptomo/dotfiles.git
  args:
    chdir: "~/misc/dotfiles"
  when: not stat_dotfiles.stat.exists

- name: init rcs
  tags:
    - setup
    - setup.dots
  command: sh setup.sh
  args:
    chdir: "~/misc/dotfiles"
  when: not stat_dotfiles.stat.exists

- name: create bundle dir
  tags:
    - setup
    - setup.dots
  file: >-
    path="~/.vim/bundle"
    state=directory

- name: clone neobundle.vim
  tags:
    - setup
    - setup.dots
  git: >-
    repo=https://github.com/Shougo/neobundle.vim.git
    dest="~/.vim/bundle/neobundle.vim"
    force=yes

- name: clone vimproc.vim
  tags:
    - setup
    - setup.dots
  git: >-
    repo=https://github.com/Shougo/vimproc.vim.git
    dest="~/.vim/bundle/vimproc.vim"
    force=yes

- stat: path="~/.vim/bundle/vimproc.vim/autoload/vimproc_linux64.so"
  register: stat_vimproc_linux64_so
  tags:
    - setup
    - setup.dots

- name: make vimproc.vim
  tags:
    - setup
    - setup.dots
  command: >-
    make clean
    chdir="~/.vim/bundle/vimproc.vim"

- name: make vimproc.vim
  tags:
    - setup
    - setup.dots
  command: >-
    make
    chdir="~/.vim/bundle/vimproc.vim"

- name: init bundles
  tags:
    - setup
    - setup.dots
  command: >-
    {{ vim_prefix }}/bin/vim
    -N -U NONE -i NONE -V1 -e -s
    --cmd "set encoding=utf-8"
    --cmd "set termencoding=utf-8"
    --cmd "source ~/.vimrc"
    --cmd "NeoBundleInstall!"
    --cmd "qall!"
  ignore_errors: yes

- name: add path
  tags:
    - setup
    - setup.dots
  shell: >-
    sed -i -e
    's!^#export PATH="$VIM:$PATH"$!export PATH="{{vim_prefix}}/bin:$PATH"!'
    ~/.bash.include

- name: update path
  tags:
    - setup
    - setup.dots
  shell: >-
    sed -i -e
    's!^export PATH="/opt/vim/.\+/bin:$PATH"$!export PATH="{{vim_prefix}}/bin:$PATH"!'
    ~/.bash.include

# vim:st=2 sts=2 sw=2:
